name: Bump Version via Comment

on: 
  issue_comment:
    types: [created, updated]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Bump Git Submodules
      uses: domdere/git-submodule-action@0.0.1
